### ISSUE TITLE
a trained model

### ISSUE THREAD

**Issue by Echo-cwb** [Iamanorange/DSSLIC#2]
Dear Iamanorange:
      Hello, I would like to ask if you have a model file that has been trained and can be used to test the effect directly. I want to see the test effect of the entire model, but I have not successfully run train.py. Thank you for your help

**Comment by Iamanorange** [comment]
I don't keep any trained model. For the performance you can refer to [the original paper](https://arxiv.org/abs/1806.03348), or try to train it by yourself.
