### ISSUE TITLE
pre-trained ADE20K model

### ISSUE THREAD

**Issue by Echo-cwb** [Iamanorange/DSSLIC#4]
Dear lamanorange:
       From the Checkpoints folder, I found there exists a pre-trained ADE20k model, but the link is invalid, I wonder if you still save this model. Thank you very much!
![捕获](https://user-images.githubusercontent.com/64060578/188253285-51b6a3d7-482b-49c3-a928-7c0b8463269c.JPG)

**Comment by Iamanorange** [comment]
These pre-trained models were uploaded by [makbari7](https://github.com/makbari7) in [his repo](https://github.com/makbari7/DSSLIC).

In #2 I already said I don't keep any model.
